### ISSUE TITLE
Safari renders a blank page. meta utf-8 should never be in the vue head

### ISSUE THREAD

**Issue by AleksejDix** [harlan-zw/unhead#10]
### Describe the bug

Framework: vue.js v3 with latest vueuse/head plugin

Recommendation in the docs should be removed.
https://unhead.harlanzw.com/guide/recipes/critical-tags

`<meta charset="utf-8">` must be in the index.html before JS is loaded.

If any bundle contains Regex which can't be encoded this will lead to following error in Safari 

https://uft8-bug.vercel.app

<img width="667" alt="Screenshot 2022-11-16 at 14 45 36" src="https://user-images.githubusercontent.com/8349161/202196965-9abde87c-ae84-4cec-beed-be7c5c3af1f1.png">

### Reproduction

https://github.com/AleksejDix/vue-head-bug-utf-8

### System Info

```Shell
System:
    OS: macOS 13.0
    CPU: (8) x64 Apple M1
    Memory: 16.95 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 106.0.5
    Safari: 16.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AleksejDix** [comment]
So I have tried different hosters and it looks like everyone is converting files to UTF when they host them but bunny CDN doesn't. Which in my opinion is correct.

I can reproduce this bug only localy or on bunny CDN

https://legal-airplane.surge.sh/

https://uft8-bug.vercel.app/

➜  dist git:(main) ✗ file -I index.html 
index.html: text/html; charset=us-ascii

**Comment by harlan-zw** [comment]
Hey @AleksejDix 

To confirm, are you SSR or running as an SPA?

These critical tags are intended for the SSR environment, maybe that can be better documented

**Comment by AleksejDix** [comment]
@harlan-zw 
tested with SPA 
and prerendered SPA

Yes, I agree this might be better documented. Just broke our production website for several hours. 🗡️

**Comment by harlan-zw** [comment]
Ah sorry about that, I have updated the doc around critical tags so it's clearer.
